default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: twitter_stack_development

test:
  <<: *default
  database: twitter_stack_test

production:
  <<: *default
  database: twitter_stack_production
  username: twitter_stack
  password: <%= ENV['TWITTER_STACK_DATABASE_PASSWORD'] %>
