# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50ee3fae0fd8cdef3fde2fc6ac68599ac0672932172b09d9b2e948fd8f60b2304955403e3426d0f0aff095415d19f1dfe54b06950d74d29fcc2f997117b072a4

test:
  secret_key_base: 8eeef641a395c08f84c14a24fdb90a51e30ee65000e6a1aee4b0d71fa45bd97759435711d13013ede97f6481ba951afa98c007bcc2d5f87a8c8fad1876091c56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
